[package]
name = "tool"
version = "0.0.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
repository = "https://github.com/idubrov/dfp"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
dfp = { path = ".." }