[package]
name = "dfp-sys"
version = "0.1.0"
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
repository = "https://github.com/idubrov/dfp"
license = "MIT/Apache-2.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
bindgen = "0.37.4"
