name: "Verify"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
